### ISSUE TITLE
Ink view not getting the touch event, when another finger or palm on the screen outside the ink view

### ISSUE THREAD

**Issue by mssaravanan** [simplifycom/ink-android#12]
My ink view has 300dp height , In my finger or palm touch out side on my ink
 view , the touch event not working

**Comment by nak5ive** [comment]
Without understanding how your parent view is constructed, I'm not sure how to help.
InkView only consumes touch events, so if you have a parent view that is intercepting the touch event and not delivering it to the view, then that would explain it. Unfortunately, I think this issue is out of scope for this project, and will be solved at a higher level in your app.
